package khelp.database.hslqdb

import khelp.database.DatabaseAccess
import java.sql.Connection
import java.sql.DriverManager

object DatabaseAccessHSQLDB : DatabaseAccess
{
    override fun createConnection(path: String): Connection
    {
        Class.forName("org.hsqldb.jdbcDriver").newInstance()
        return DriverManager.getConnection("jdbc:hsqldb:file:$path", "SA", "")
    }

    override fun checkIfTableExists() = false
    override fun shutdownCommand() = "SHUTDOWN"
    override fun shortTextType() = "VARCHAR(16)"
    override fun longTextType() = "LONGVARCHAR"
    override fun primaryKeyDeclaration() = "INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY"
}