package khelp.database.hslqdb

import khelp.database.DatabaseAccess
import java.sql.Connection
import java.sql.DriverManager

/**
 * HSQLDB specific operations/settings
 */
object DatabaseAccessHSQLDB : DatabaseAccess
{
    /**
     * Create a connection
     * @param path File path
     * @return Connection created
     */
    override fun createConnection(path: String): Connection
    {
        Class.forName("org.hsqldb.jdbcDriver").newInstance()
        return DriverManager.getConnection("jdbc:hsqldb:file:$path", "SA", "")
    }

    /**Indicates if the check of table exists on create is possible*/
    override fun checkIfTableExists() = false

    /**Command use for shutdown the database (empty if none)*/
    override fun shutdownCommand() = "SHUTDOWN"

    /**Short text declaration (for 16 bytes long text)*/
    override fun shortTextType() = "VARCHAR(16)"

    /**Long text declaration*/
    override fun longTextType() = "LONGVARCHAR"

    /**Primary key declaration*/
    override fun primaryKeyDeclaration() = "INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY"
}